#!/usr/bin/env node
// Codex CLI -> Marveen hook shim (agent-agnostic Phase 2).
//
// Codex hooks receive nearly the same JSON as Claude Code hooks on stdin
// (session_id, cwd, hook_event_name, tool_name, tool_input, ...; verified
// 2026-09-22, learn.chatgpt.com/docs/hooks) and honour the same replies
// (exit 2 = block; stdout JSON with hookSpecificOutput.permissionDecision).
// So the shim only (1) maps Codex tool names onto the Claude names the 29
// governance scripts match on, (2) runs the ORIGINAL command unchanged with
// the translated payload on its stdin, and (3) forwards stdout + exit code.
//
// Usage (generated by bundle-render):  node codex-hook.mjs b64:<base64 of original command>
// A missing/undecodable argument BLOCKS (exit 2): a gate that cannot run must
// fail closed, mirroring the governance-kapu convention in settings.json.

import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const CODEX_TO_CLAUDE_TOOL = {
  shell: 'Bash', exec_command: 'Bash', local_shell: 'Bash', Bash: 'Bash', bash: 'Bash',
  apply_patch: 'Edit', web_search: 'WebSearch',
}

function mapToolName(name) {
  if (typeof name !== 'string') return name
  return CODEX_TO_CLAUDE_TOOL[name] ?? name
}

function main() {
  const arg = process.argv[2] ?? ''
  if (!arg.startsWith('b64:')) {
    process.stderr.write('codex-hook shim: missing b64:<command> argument -- blocking (fail closed)\n')
    process.exit(2)
  }
  let command
  try { command = Buffer.from(arg.slice(4), 'base64').toString('utf-8') } catch {
    process.stderr.write('codex-hook shim: undecodable command -- blocking (fail closed)\n')
    process.exit(2)
  }
  let raw = ''
  try { raw = readFileSync(0, 'utf-8') } catch { raw = '' }
  let payload = {}
  try { payload = raw.trim() ? JSON.parse(raw) : {} } catch { payload = { _raw: raw } }
  if (payload && typeof payload === 'object') {
    if ('tool_name' in payload) payload.tool_name = mapToolName(payload.tool_name)
    payload._marveen_runtime = 'codex-cli'
  }
  const res = spawnSync('/bin/sh', ['-c', command], {
    input: JSON.stringify(payload),
    encoding: 'utf-8',
    env: { ...process.env, MARVEEN_HOOK_RUNTIME: 'codex-cli' },
    maxBuffer: 8 * 1024 * 1024,
  })
  if (res.stdout) process.stdout.write(res.stdout)
  if (res.stderr) process.stderr.write(res.stderr)
  if (res.error) {
    process.stderr.write(`codex-hook shim: failed to run hook: ${res.error.message}\n`)
    process.exit(2)
  }
  process.exit(res.status ?? 2)
}

main()
