#!/usr/bin/env node
// Gemini CLI -> Marveen hook shim (agent-agnostic Phase 3).
//
// Gemini hooks receive {session_id, transcript_path, cwd, hook_event_name,
// timestamp, tool_name, tool_input, tool_response?, prompt?} on stdin
// (gemini-cli 0.60.0 source, hookEventHandler.createBaseInput) and read a
// reply of exit 2 (system block) or stdout JSON {decision: "deny"|"block",
// reason, hookSpecificOutput: {additionalContext, tool_input}}.
//
// The 29 Marveen governance scripts speak the Claude Code dialect: Claude
// event names (PreToolUse...), Claude tool names (Bash, WebFetch...), replies
// of exit 2 / {hookSpecificOutput: {permissionDecision: "deny", ...}} and plain
// stdout text as injected context. This shim translates both directions.
//
// Usage (generated by bundle-render):  node gemini-hook.mjs <ClaudeEvent> b64:<base64 of original command>

import { spawnSync } from 'node:child_process'
import { readFileSync } from 'node:fs'

const GEMINI_TO_CLAUDE_TOOL = {
  run_shell_command: 'Bash', write_file: 'Write', replace: 'Edit', read_file: 'Read', read_many_files: 'Read',
  web_fetch: 'WebFetch', google_web_search: 'WebSearch', glob: 'Glob', grep_search: 'Grep', search_file_content: 'Grep',
  list_directory: 'Bash', save_memory: 'Write',
}

function main() {
  const claudeEvent = process.argv[2] ?? ''
  const arg = process.argv[3] ?? ''
  if (!claudeEvent || !arg.startsWith('b64:')) {
    process.stderr.write('gemini-hook shim: usage <ClaudeEvent> b64:<command> -- blocking (fail closed)\n')
    process.exit(2)
  }
  let command
  try { command = Buffer.from(arg.slice(4), 'base64').toString('utf-8') } catch {
    process.stderr.write('gemini-hook shim: undecodable command -- blocking (fail closed)\n')
    process.exit(2)
  }
  let raw = ''
  try { raw = readFileSync(0, 'utf-8') } catch { raw = '' }
  let payload = {}
  try { payload = raw.trim() ? JSON.parse(raw) : {} } catch { payload = { _raw: raw } }
  if (payload && typeof payload === 'object') {
    payload.hook_event_name = claudeEvent
    if (typeof payload.tool_name === 'string') payload.tool_name = GEMINI_TO_CLAUDE_TOOL[payload.tool_name] ?? payload.tool_name
    payload._marveen_runtime = 'gemini-cli'
  }
  const res = spawnSync('/bin/sh', ['-c', command], {
    input: JSON.stringify(payload), encoding: 'utf-8',
    env: { ...process.env, MARVEEN_HOOK_RUNTIME: 'gemini-cli' }, maxBuffer: 8 * 1024 * 1024,
  })
  if (res.stderr) process.stderr.write(res.stderr)
  if (res.error) { process.stderr.write(`gemini-hook shim: failed to run hook: ${res.error.message}\n`); process.exit(2) }
  const out = (res.stdout ?? '').trim()
  if (res.status === 2) {
    // Claude "block": stderr carries the reason; Gemini treats exit 2 as a system block.
    if (out) process.stdout.write(translateReply(out, claudeEvent, true) + '\n')
    process.exit(2)
  }
  if (res.status !== 0) process.exit(res.status ?? 2)
  if (out) process.stdout.write(translateReply(out, claudeEvent, false) + '\n')
  process.exit(0)
}

/** Claude reply -> Gemini reply. Non-JSON stdout is injected context in Claude; Gemini wants it under hookSpecificOutput.additionalContext. */
export function translateReply(out, claudeEvent, blocked) {
  let obj = null
  try { obj = JSON.parse(out) } catch { obj = null }
  if (!obj || typeof obj !== 'object') {
    return JSON.stringify({ hookSpecificOutput: { hookEventName: claudeEvent, additionalContext: out } })
  }
  const hso = obj.hookSpecificOutput && typeof obj.hookSpecificOutput === 'object' ? obj.hookSpecificOutput : {}
  const deny = blocked || obj.decision === 'block' || obj.decision === 'deny' || hso.permissionDecision === 'deny'
  const reason = obj.reason ?? hso.permissionDecisionReason ?? obj.stopReason ?? (deny ? 'blocked by Marveen governance hook' : undefined)
  const reply = { ...obj }
  if (deny) { reply.decision = 'deny'; if (reason) reply.reason = reason }
  const extra = { ...hso }
  if (hso.updatedInput && typeof hso.updatedInput === 'object') extra.tool_input = hso.updatedInput
  if (typeof obj.additionalContext === 'string') extra.additionalContext = obj.additionalContext
  if (Object.keys(extra).length) reply.hookSpecificOutput = { hookEventName: claudeEvent, ...extra }
  return JSON.stringify(reply)
}

if (process.argv[1] && process.argv[1].endsWith('gemini-hook.mjs')) main()
