// Agent-bundle rendering for non-Claude runtimes (Phase 2).
//
// The source of truth stays what the fleet already maintains per agent:
// CLAUDE.md + SOUL.md (instructions), .mcp.json (MCP servers) and
// .claude/settings.json (hooks + permissions). Each runtime adapter renders
// its native files FROM those, so an operator edits one bundle and every
// runtime sees the same agent. Pure functions: the adapters do the I/O.
//
// Codex targets (docs verified 2026-09-22, learn.chatgpt.com/docs/*):
//   AGENTS.md                 -- instructions (global ~/.codex/AGENTS.md, then
//                                project root down to cwd; project_doc_max_bytes)
//   $CODEX_HOME/config.toml   -- model, approval_policy, sandbox_mode,
//                                [sandbox_workspace_write], [mcp_servers.<id>],
//                                [features] hooks, [projects."<dir>"] trust
//   <dir>/.codex/hooks.json   -- {"hooks": {Event: [{matcher, hooks:[{type,command,timeout}]}]}}

export interface McpServerDef {
  command?: string
  args?: string[]
  env?: Record<string, string>
  url?: string
  headers?: Record<string, string>
  type?: string
  [k: string]: unknown
}

export interface ClaudeHookEntry {
  type?: string            // 'command' | 'agent'
  command?: string
  prompt?: string
  timeout?: number         // seconds in Claude Code
}

export interface ClaudeHookGroup {
  matcher?: string
  hooks?: ClaudeHookEntry[]
}

export type ClaudeHooksConfig = Record<string, ClaudeHookGroup[]>

// --- AGENTS.md ---------------------------------------------------------------

export interface InstructionsSource {
  displayName?: string
  claudeMd: string | null
  soulMd: string | null
  /** Optional index of skill names -> relative SKILL.md paths. */
  skills?: Array<{ name: string; path: string; description?: string }>
}

/** Render a runtime-neutral instructions file (AGENTS.md / GEMINI.md). */
export function renderInstructionsMd(src: InstructionsSource, opts: { target: 'AGENTS.md' | 'GEMINI.md' }): string {
  const parts: string[] = []
  parts.push(`<!-- Generated by Marveen bundle-render from CLAUDE.md + SOUL.md. Edit those, not this ${opts.target}. -->`)
  if (src.displayName) parts.push(`# ${src.displayName}`)
  if (src.claudeMd?.trim()) parts.push(src.claudeMd.trim())
  if (src.soulMd?.trim()) parts.push('## Személyiség (SOUL.md)\n\n' + src.soulMd.trim())
  if (src.skills && src.skills.length) {
    const lines = src.skills.map((s) => `- **${s.name}** (\`${s.path}\`)${s.description ? `: ${s.description}` : ''}`)
    parts.push('## Skillek\n\nOlvasd be a megfelelő SKILL.md-t, mielőtt a feladatba kezdesz:\n\n' + lines.join('\n'))
  }
  return parts.join('\n\n') + '\n'
}

// --- TOML helpers --------------------------------------------------------------

export function tomlString(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t') + '"'
}

function tomlArray(values: string[]): string {
  return '[' + values.map(tomlString).join(', ') + ']'
}

function tomlInlineTable(obj: Record<string, string>): string {
  return '{ ' + Object.entries(obj).map(([k, v]) => `${tomlKey(k)} = ${tomlString(v)}`).join(', ') + ' }'
}

function tomlKey(k: string): string {
  return /^[A-Za-z0-9_-]+$/.test(k) ? k : tomlString(k)
}

// --- Codex config.toml ---------------------------------------------------------

export type CodexSandboxMode = 'read-only' | 'workspace-write' | 'danger-full-access'

export interface CodexConfigOptions {
  model: string
  sandboxMode: CodexSandboxMode
  /** Only meaningful with workspace-write. Agents fetch the web, so default true. */
  networkAccess: boolean
  approvalPolicy: 'never' | 'on-request'
  /** Agent working dir: trusted so no prompt ever parks a headless run. */
  projectDir: string
  hooksEnabled: boolean
  projectDocMaxBytes?: number
  modelContextWindow?: number
  mcpServers: Record<string, McpServerDef>
  writableRoots?: string[]
  /** history.persistence: "save-all" (default) | "none" */
  historyPersistence?: 'save-all' | 'none'
}

export function renderCodexConfigToml(o: CodexConfigOptions): string {
  const L: string[] = []
  L.push('# Generated by Marveen bundle-render (agent-agnostic runtime). Do not edit by hand.')
  L.push(`model = ${tomlString(o.model)}`)
  L.push(`approval_policy = ${tomlString(o.approvalPolicy)}`)
  L.push(`sandbox_mode = ${tomlString(o.sandboxMode)}`)
  L.push(`project_doc_max_bytes = ${o.projectDocMaxBytes ?? 131072}`)
  if (o.modelContextWindow) L.push(`model_context_window = ${o.modelContextWindow}`)
  if (o.historyPersistence) L.push(`history.persistence = ${tomlString(o.historyPersistence)}`)
  L.push('')
  if (o.sandboxMode === 'workspace-write') {
    L.push('[sandbox_workspace_write]')
    L.push(`network_access = ${o.networkAccess ? 'true' : 'false'}`)
    if (o.writableRoots && o.writableRoots.length) L.push(`writable_roots = ${tomlArray(o.writableRoots)}`)
    L.push('')
  }
  L.push('[features]')
  L.push(`hooks = ${o.hooksEnabled ? 'true' : 'false'}`)
  L.push('')
  L.push(`[projects.${tomlString(o.projectDir)}]`)
  L.push('trust_level = "trusted"')
  L.push('')
  for (const [name, def] of Object.entries(o.mcpServers)) {
    const key = name.replace(/[^A-Za-z0-9_-]/g, '_')
    L.push(`[mcp_servers.${key}]`)
    if (def.url) {
      L.push(`url = ${tomlString(def.url)}`)
      if (def.headers && Object.keys(def.headers).length) L.push(`http_headers = ${tomlInlineTable(def.headers)}`)
    } else if (def.command) {
      L.push(`command = ${tomlString(def.command)}`)
      if (def.args && def.args.length) L.push(`args = ${tomlArray(def.args)}`)
      if (def.env && Object.keys(def.env).length) L.push(`env = ${tomlInlineTable(def.env)}`)
    }
    L.push('enabled = true')
    L.push('')
  }
  return L.join('\n')
}

// --- Hooks: Claude settings.json -> Codex hooks.json ------------------------------

/** Claude Code hook events -> Codex hook events (null = no equivalent). */
export const CLAUDE_TO_CODEX_EVENT: Record<string, string | null> = {
  PreToolUse: 'PreToolUse',
  PostToolUse: 'PostToolUse',
  UserPromptSubmit: 'UserPromptSubmit',
  SessionStart: 'SessionStart',
  SessionEnd: 'SessionEnd',
  Stop: 'Stop',
  SubagentStop: 'SubagentStop',
  PreCompact: 'PreCompact',
  Notification: null,
}

/** Claude Code tool names as they appear in matchers -> Codex tool names. */
export const CLAUDE_TO_CODEX_TOOL: Record<string, string> = {
  Bash: 'Bash',
  Edit: 'apply_patch',
  Write: 'apply_patch',
  MultiEdit: 'apply_patch',
  NotebookEdit: 'apply_patch',
  WebSearch: 'web_search',
}

export interface CodexHookEntry { type: 'command'; command: string; timeout?: number }
export interface CodexHookGroup { matcher?: string; hooks: CodexHookEntry[] }
export interface CodexHooksFile { description: string; hooks: Record<string, CodexHookGroup[]> }

/**
 * Wrap each Claude command hook in the Codex shim (scripts/hooks/shim/codex-hook.mjs),
 * which translates the payload/tool names and forwards exit codes. The
 * original command travels base64-encoded so no shell quoting can break it.
 */
export function renderCodexHooksJson(
  claudeHooks: ClaudeHooksConfig | null | undefined,
  opts: { shimCommand: string },
): { file: CodexHooksFile; skipped: string[] } {
  const out: Record<string, CodexHookGroup[]> = {}
  const skipped: string[] = []
  for (const [event, groups] of Object.entries(claudeHooks ?? {})) {
    const target = CLAUDE_TO_CODEX_EVENT[event]
    if (target === undefined) { skipped.push(`${event}: unknown Claude event`); continue }
    if (target === null) { skipped.push(`${event}: no Codex equivalent`); continue }
    for (const g of groups ?? []) {
      const hooks: CodexHookEntry[] = []
      for (const h of g.hooks ?? []) {
        if (h.type !== 'command' || !h.command) { skipped.push(`${event}: ${h.type ?? 'unknown'}-type hook has no command equivalent`); continue }
        const b64 = Buffer.from(h.command, 'utf-8').toString('base64')
        hooks.push({ type: 'command', command: `${opts.shimCommand} b64:${b64}`, ...(h.timeout ? { timeout: h.timeout } : {}) })
      }
      if (!hooks.length) continue
      const group: CodexHookGroup = { hooks }
      if (g.matcher) group.matcher = translateMatcher(g.matcher, CLAUDE_TO_CODEX_TOOL)
      ;(out[target] ??= []).push(group)
    }
  }
  return { file: { description: 'Generated by Marveen bundle-render from .claude/settings.json hooks.', hooks: out }, skipped }
}

/** Rewrite bare tool names inside a `A|B|.*x.*` matcher with the alias table; keep regexes. */
export function translateMatcher(matcher: string, alias: Record<string, string>): string {
  const parts = matcher.split('|').map((p) => {
    const t = p.trim()
    const mapped = alias[t]
    return mapped ?? t
  })
  return [...new Set(parts)].join('|')
}
