import { describe, it, expect } from 'vitest'
import {
  renderInstructionsMd, renderCodexConfigToml, renderCodexHooksJson, translateMatcher, tomlString, CLAUDE_TO_CODEX_TOOL,
} from '../runtime/bundle-render.js'

describe('renderInstructionsMd', () => {
  it('joins CLAUDE.md + SOUL.md + skills with a generated-file banner', () => {
    const md = renderInstructionsMd({
      displayName: 'Argus', claudeMd: '# Argus\nTe vagy Argus.', soulMd: 'Nyugodt, precíz.',
      skills: [{ name: 'deep-research', path: '.claude/skills/deep-research/SKILL.md', description: 'Mély kutatás' }],
    }, { target: 'AGENTS.md' })
    expect(md.startsWith('<!-- Generated by Marveen bundle-render')).toBe(true)
    expect(md).toContain('Edit those, not this AGENTS.md')
    expect(md).toContain('# Argus')
    expect(md).toContain('## Személyiség (SOUL.md)\n\nNyugodt, precíz.')
    expect(md).toContain('**deep-research** (`.claude/skills/deep-research/SKILL.md`): Mély kutatás')
    expect(md.endsWith('\n')).toBe(true)
  })
  it('tolerates missing parts', () => {
    const md = renderInstructionsMd({ claudeMd: null, soulMd: null }, { target: 'GEMINI.md' })
    expect(md).toContain('GEMINI.md')
    expect(md).not.toContain('Személyiség')
  })
})

describe('tomlString', () => {
  it('escapes quotes, backslashes and newlines', () => {
    expect(tomlString('a"b\\c\nd')).toBe('"a\\"b\\\\c\\nd"')
  })
})

describe('renderCodexConfigToml', () => {
  const toml = renderCodexConfigToml({
    model: 'gpt-5.6-sol', sandboxMode: 'workspace-write', networkAccess: true, approvalPolicy: 'never',
    projectDir: '/home/balint/marveen-agnostic/agents/scout', hooksEnabled: true,
    mcpServers: {
      gmail: { command: 'npx', args: ['-y', 'gmail-mcp-server@latest'], env: { GMAIL_CLIENT_ID: 'x' } },
      'marveen-channel': { url: 'http://127.0.0.1:3421/mcp', headers: { Authorization: 'Bearer t' } },
    },
  })
  it('core keys', () => {
    expect(toml).toContain('model = "gpt-5.6-sol"')
    expect(toml).toContain('approval_policy = "never"')
    expect(toml).toContain('sandbox_mode = "workspace-write"')
    expect(toml).toContain('[sandbox_workspace_write]\nnetwork_access = true')
    expect(toml).toContain('[features]\nhooks = true')
    expect(toml).toContain('[projects."/home/balint/marveen-agnostic/agents/scout"]\ntrust_level = "trusted"')
    expect(toml).toContain('project_doc_max_bytes = 131072')
  })
  it('MCP servers: stdio and HTTP forms', () => {
    expect(toml).toContain('[mcp_servers.gmail]\ncommand = "npx"\nargs = ["-y", "gmail-mcp-server@latest"]\nenv = { GMAIL_CLIENT_ID = "x" }\nenabled = true')
    expect(toml).toContain('[mcp_servers.marveen-channel]\nurl = "http://127.0.0.1:3421/mcp"\nhttp_headers = { Authorization = "Bearer t" }\nenabled = true')
  })
  it('read-only sandbox has no workspace-write table', () => {
    const ro = renderCodexConfigToml({ model: 'm', sandboxMode: 'read-only', networkAccess: false, approvalPolicy: 'never', projectDir: '/d', hooksEnabled: false, mcpServers: {} })
    expect(ro).not.toContain('[sandbox_workspace_write]')
    expect(ro).toContain('hooks = false')
  })
})

describe('renderCodexHooksJson', () => {
  const claudeHooks = {
    PreToolUse: [
      { matcher: 'Bash|.*send_email.*|.*manage_email.*', hooks: [{ type: 'command', command: '"/usr/bin/node" "/x/scripts/email-send-gate.mjs"', timeout: 10 }] },
      { matcher: 'WebFetch', hooks: [{ type: 'command', command: 'node /x/scripts/hooks/egress-gate.mjs', timeout: 10 }] },
    ],
    PreCompact: [{ matcher: 'auto', hooks: [{ type: 'agent', prompt: 'mentsd a memóriát', timeout: 180 }] }],
    UserPromptSubmit: [{ hooks: [{ type: 'command', command: "bash -c '[ -f /x/p.py ] && exec python3 /x/p.py; exit 0'", timeout: 10 }] }],
    Notification: [{ hooks: [{ type: 'command', command: 'echo hi' }] }],
  }
  const { file, skipped } = renderCodexHooksJson(claudeHooks, { shimCommand: '/usr/bin/node /x/scripts/hooks/shim/codex-hook.mjs' })
  it('wraps command hooks in the shim with a base64 payload (quoting-proof)', () => {
    const pre = file.hooks.PreToolUse
    expect(pre).toHaveLength(2)
    const cmd = pre[0].hooks[0].command
    expect(cmd.startsWith('/usr/bin/node /x/scripts/hooks/shim/codex-hook.mjs b64:')).toBe(true)
    const decoded = Buffer.from(cmd.split('b64:')[1], 'base64').toString('utf-8')
    expect(decoded).toBe('"/usr/bin/node" "/x/scripts/email-send-gate.mjs"')
    expect(pre[0].hooks[0].timeout).toBe(10)
    expect(pre[0].matcher).toBe('Bash|.*send_email.*|.*manage_email.*')
  })
  it('keeps UserPromptSubmit (no matcher) and skips agent-type / unsupported events with reasons', () => {
    expect(file.hooks.UserPromptSubmit[0].matcher).toBeUndefined()
    expect(file.hooks.PreCompact).toBeUndefined()
    expect(file.hooks.Notification).toBeUndefined()
    expect(skipped.some((s) => s.startsWith('PreCompact: agent-type'))).toBe(true)
    expect(skipped.some((s) => s.startsWith('Notification: no Codex equivalent'))).toBe(true)
  })
  it('null/undefined input renders an empty hooks file', () => {
    expect(renderCodexHooksJson(null, { shimCommand: 'x' }).file.hooks).toEqual({})
  })
})

describe('translateMatcher', () => {
  it('maps bare Claude tool names, keeps regex fragments, dedupes', () => {
    expect(translateMatcher('Write|Edit|NotebookEdit|Bash', CLAUDE_TO_CODEX_TOOL)).toBe('apply_patch|Bash')
    expect(translateMatcher('Bash|.*send_email.*', CLAUDE_TO_CODEX_TOOL)).toBe('Bash|.*send_email.*')
  })
})
